--- 

- name: set security model on controller
  command: /bin/nsxcli -c "set control-cluster security-model shared-secret secret {{ctr_shared_secret}}"

- name: pause 5 minutes for service ready  
  wait_for: host={{ctr1_ip}} port=7777 state=present delay=300 timeout=360

- name: Controller Cluster Initialization
  command: /bin/nsxcli -c  initialize control-cluster
  delegate_to: "{{ctr1_ip}}"

- name: get controller 2 thumbprint 
  command: /bin/nsxcli -c get control-cluster certificate thumbprint
  register: key2
  delegate_to: "{{ctr2_ip}}"

- name: get controller 3 thumbprint
  command: /bin/nsxcli -c get control-cluster certificate thumbprint
  register: key3
  delegate_to: "{{ctr3_ip}}"

- name: pause 5 minutes for service ready
  wait_for: host={{ctr1_ip}} port=7777 state=present delay=180 timeout=360

- name: get controller 2 into controller cluster 
  command: /bin/nsxcli -c join control-cluster {{ctr2_ip}} thumbprint {{item.thumb2}}
  delegate_to: "{{ctr1_ip}}"
  with_items:
    - { thumb2: "{{key2.stdout}}" }

- name: activate controller 2
  command: /bin/nsxcli -c activate control-cluster
  delegate_to: "{{ctr2_ip}}"

- name: pause 5 minutes for service ready
  wait_for: host={{ctr1_ip}} port=7777 state=present delay=180 timeout=360

- name: get controller 3 into controller cluster
  command: /bin/nsxcli -c join control-cluster {{ctr3_ip}} thumbprint {{item.thumb3}}
  delegate_to: "{{ctr1_ip}}"
  with_items:
    - { thumb3: "{{key3.stdout}}" }

- name: activate controller 3
  command: /bin/nsxcli -c activate control-cluster
  delegate_to: "{{ctr3_ip}}"

