---

- name: copy nsx vib file to esx 
  copy: src=/root/ansible/software/nsx-lcp-1.0.0.0.0.3654016-esx60.zip dest=/tmp/nsx-lcp-1.0.0.0.0.3654016-esx60.zip

- name: host preparation 
  command: esxcli software vib install -d /tmp/nsx-lcp-1.0.0.0.0.3654016-esx60.zip

